name: Daily Word Bot
on:
  schedule:
    - cron: '7 16 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Run Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node index.mjs
      - name: Commit Changes
        run: |
          git config --global user.name "WordBot"
          git config --global user.email "actions@github.com"
          git add current_word.txt word_history.json
          git commit -m "Update history [skip ci]" || echo "No changes"
          git push
